import 'package:flutter/material.dart';
import 'package:flutterapp/testeapp/generatedindividualchatwidget/generated/GeneratedEllipseWidget13.dart';
import 'package:flutterapp/testeapp/generatedindividualchatwidget/generated/GeneratedStatusBarWidget8.dart';
import 'package:flutterapp/testeapp/generatedindividualchatwidget/generated/GeneratedEllipseWidget12.dart';
import 'package:flutterapp/testeapp/generatedindividualchatwidget/generated/GeneratedRectangleWidget18.dart';
import 'package:flutterapp/testeapp/generatedindividualchatwidget/generated/GeneratedEllipseWidget11.dart';
import 'package:flutterapp/testeapp/generatedindividualchatwidget/generated/GeneratedReallyloveyourmostrecentphotoIvebeentryingtocapturethes.dart';
import 'package:flutterapp/testeapp/generatedindividualchatwidget/generated/GeneratedThankyouThatwasveryhelpfulWidget.dart';
import 'package:flutterapp/testeapp/generatedindividualchatwidget/generated/GeneratedTabBarWidget3.dart';
import 'package:flutterapp/testeapp/generatedindividualchatwidget/generated/GeneratedRectangle2Widget25.dart';
import 'package:flutterapp/testeapp/generatedindividualchatwidget/generated/GeneratedNavigationBarWidget.dart';
import 'package:flutterapp/testeapp/generatedindividualchatwidget/generated/GeneratedAfast50mmlikef18wouldhelpwiththebokehIvebeenusingprimes.dart';
import 'package:flutterapp/testeapp/generatedindividualchatwidget/generated/GeneratedRectangle21Widget11.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/testeapp/generatedindividualchatwidget/generated/GeneratedRectangle22Widget3.dart';

/* Frame Individual chat
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIndividualchatWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 812.0,
                      child: GeneratedRectangleWidget18(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth;

                        final double height =
                            constraints.maxHeight * 0.10837438423645321;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: 0,
                              y: 0,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedNavigationBarWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.07466666666666667;
                        double scaleX =
                            (constraints.maxWidth * percentWidth) / 28.0;

                        double percentHeight = 0.034482758620689655;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) / 28.0;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.042666666666666665,
                              translateY:
                                  constraints.maxHeight * 0.15024630541871922,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedEllipseWidget11())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.07466666666666667;
                        double scaleX =
                            (constraints.maxWidth * percentWidth) / 28.0;

                        double percentHeight = 0.034482758620689655;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) / 28.0;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.8826666666666667,
                              translateY:
                                  constraints.maxHeight * 0.28078817733990147,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedEllipseWidget12())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 60.0,
                      top: 120.0,
                      right: null,
                      bottom: null,
                      width: 299.0,
                      height: 84.0,
                      child: GeneratedRectangle2Widget25(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.7226666666666667;

                        final double height =
                            constraints.maxHeight * 0.0665024630541872;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.20266666666666666,
                              y: constraints.maxHeight * 0.16748768472906403,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child:
                                    GeneratedReallyloveyourmostrecentphotoIvebeentryingtocapturethes(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.07466666666666667;
                        double scaleX =
                            (constraints.maxWidth * percentWidth) / 28.0;

                        double percentHeight = 0.034482758620689655;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) / 28.0;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.042666666666666665,
                              translateY:
                                  constraints.maxHeight * 0.41625615763546797,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedEllipseWidget13())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 60.0,
                      top: 336.0,
                      right: null,
                      bottom: null,
                      width: 299.0,
                      height: 50.0,
                      child: GeneratedRectangle22Widget3(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.7226666666666667;

                        final double height =
                            constraints.maxHeight * 0.024630541871921183;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.20266666666666666,
                              y: constraints.maxHeight * 0.43349753694581283,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child:
                                    GeneratedThankyouThatwasveryhelpfulWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 228.0,
                      right: null,
                      bottom: null,
                      width: 299.0,
                      height: 84.0,
                      child: GeneratedRectangle21Widget11(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.7226666666666667;

                        final double height =
                            constraints.maxHeight * 0.0665024630541872;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.08533333333333333,
                              y: constraints.maxHeight * 0.30049261083743845,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child:
                                    GeneratedAfast50mmlikef18wouldhelpwiththebokehIvebeenusingprimes(),
                              ))
                        ]);
                      }),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: 0.0,
              width: 375.0,
              height: 83.0,
              child: GeneratedTabBarWidget3(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedStatusBarWidget8(),
            )
          ]),
    ));
  }
}
