import 'package:flutter/material.dart';
import 'package:flutterapp/testeapp/generatedprofilewidget/generated/GeneratedEllipseWidget2.dart';
import 'package:flutterapp/testeapp/generatedprofilewidget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/testeapp/generatedprofilewidget/generated/GeneratedRectangle21Widget2.dart';
import 'package:flutterapp/testeapp/generatedprofilewidget/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/testeapp/generatedprofilewidget/generated/GeneratedStatusBarWidget4.dart';
import 'package:flutterapp/testeapp/generatedprofilewidget/generated/GeneratedButtonWidget7.dart';
import 'package:flutterapp/testeapp/generatedprofilewidget/generated/GeneratedRectangle2Widget12.dart';
import 'package:flutterapp/testeapp/generatedprofilewidget/generated/GeneratedButtonWidget5.dart';
import 'package:flutterapp/testeapp/generatedprofilewidget/generated/GeneratedSanfranciscocaWidget.dart';
import 'package:flutterapp/testeapp/generatedprofilewidget/generated/GeneratedRectangleWidget10.dart';
import 'package:flutterapp/testeapp/generatedprofilewidget/generated/GeneratedButtonWidget6.dart';
import 'package:flutterapp/testeapp/generatedprofilewidget/generated/GeneratedTabBarWidget.dart';
import 'package:flutterapp/testeapp/generatedprofilewidget/generated/GeneratedRectangle23Widget.dart';
import 'package:flutterapp/testeapp/generatedprofilewidget/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/testeapp/generatedprofilewidget/generated/GeneratedJaneWidget.dart';

/* Frame Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1549.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 1549.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 812.0,
                                    child: GeneratedRectangleWidget10(),
                                  ),
                                  Positioned(
                                    left: 124.0,
                                    top: 76.0,
                                    right: null,
                                    bottom: null,
                                    width: 128.0,
                                    height: 128.0,
                                    child: GeneratedEllipseWidget2(),
                                  ),
                                  Positioned(
                                    left: 142.0,
                                    top: 236.0,
                                    right: null,
                                    bottom: null,
                                    width: 97.0,
                                    height: 45.0,
                                    child: GeneratedJaneWidget(),
                                  ),
                                  Positioned(
                                    left: 121.0,
                                    top: 292.0,
                                    right: null,
                                    bottom: null,
                                    width: 135.0,
                                    height: 17.0,
                                    child: GeneratedSanfranciscocaWidget(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 491.0,
                                    right: null,
                                    bottom: null,
                                    width: 167.0,
                                    height: 220.0,
                                    child: GeneratedRectangle2Widget12(),
                                  ),
                                  Positioned(
                                    left: 192.0,
                                    top: 1130.0,
                                    right: null,
                                    bottom: null,
                                    width: 167.0,
                                    height: 220.0,
                                    child: GeneratedRectangle25Widget(),
                                  ),
                                  Positioned(
                                    left: 192.0,
                                    top: 491.0,
                                    right: null,
                                    bottom: null,
                                    width: 167.0,
                                    height: 310.0,
                                    child: GeneratedRectangle21Widget2(),
                                  ),
                                  Positioned(
                                    left: 192.0,
                                    top: 811.0,
                                    right: null,
                                    bottom: null,
                                    width: 167.0,
                                    height: 310.0,
                                    child: GeneratedRectangle23Widget(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 1040.0,
                                    right: null,
                                    bottom: null,
                                    width: 167.0,
                                    height: 310.0,
                                    child: GeneratedRectangle24Widget(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 721.0,
                                    right: null,
                                    bottom: null,
                                    width: 167.0,
                                    height: 310.0,
                                    child: GeneratedRectangle22Widget(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 1382.0,
                                    right: null,
                                    bottom: null,
                                    width: 343.0,
                                    height: 52.0,
                                    child: GeneratedButtonWidget5(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 339.0,
                                    right: null,
                                    bottom: null,
                                    width: 343.0,
                                    height: 52.0,
                                    child: GeneratedButtonWidget6(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 407.0,
                                    right: null,
                                    bottom: null,
                                    width: 343.0,
                                    height: 52.0,
                                    child: GeneratedButtonWidget7(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: 0.0,
              width: 375.0,
              height: 83.0,
              child: GeneratedTabBarWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedStatusBarWidget4(),
            )
          ]),
    ));
  }
}
