import 'package:flutter/material.dart';
import 'package:flutterapp/testeapp/generatedseehowitworkswidget/generated/Generated1Widget.dart';
import 'package:flutterapp/testeapp/generatedseehowitworkswidget/generated/Generated2Widget.dart';
import 'package:flutterapp/testeapp/generatedseehowitworkswidget/generated/GeneratedPresetSizesWidget1.dart';
import 'package:flutterapp/testeapp/generatedseehowitworkswidget/generated/GeneratedSeehowitworksWidget1.dart';
import 'package:flutterapp/testeapp/generatedseehowitworkswidget/generated/GeneratedPresetSizesWidget.dart';
import 'package:flutterapp/testeapp/generatedseehowitworkswidget/generated/GeneratedViewtheprototypeWidget.dart';
import 'package:flutterapp/testeapp/generatedseehowitworkswidget/generated/GeneratedGroupWidget.dart';
import 'package:flutterapp/testeapp/generatedseehowitworkswidget/generated/GeneratedPresetSizesWidget3.dart';
import 'package:flutterapp/testeapp/generatedseehowitworkswidget/generated/GeneratedRightPanelWidget.dart';
import 'package:flutterapp/testeapp/generatedseehowitworkswidget/generated/GeneratedGetstartedbyclickingtheplayiconinthetoprightoftheeditor.dart';
import 'package:flutterapp/testeapp/generatedseehowitworkswidget/generated/GeneratedLeftPanelWidget.dart';
import 'package:flutterapp/testeapp/generatedseehowitworkswidget/generated/GeneratedPresetSizesWidget4.dart';
import 'package:flutterapp/testeapp/generatedseehowitworkswidget/generated/GeneratedTakealookathowtheseprototypesaremadeandwhatsettingsandf.dart';
import 'package:flutterapp/testeapp/generatedseehowitworkswidget/generated/GeneratedPresetSizesWidget2.dart';

/* Group See how it works
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSeehowitworksWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 3352.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 9302.0,
                    height: 3352.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 1191.0,
                            height: 3352.0,
                            child: GeneratedLeftPanelWidget(),
                          ),
                          Positioned(
                            left: 100.0,
                            top: 301.0,
                            right: null,
                            bottom: null,
                            width: 97.0,
                            height: 293.0,
                            child: Generated2Widget(),
                          ),
                          Positioned(
                            left: 100.0,
                            top: 21.0,
                            right: null,
                            bottom: null,
                            width: 97.0,
                            height: 293.0,
                            child: Generated1Widget(),
                          ),
                          Positioned(
                            left: null,
                            top: 187.0,
                            right: 8671.0,
                            bottom: null,
                            width: 40.0,
                            height: 40.0,
                            child: GeneratedGroupWidget(),
                          ),
                          Positioned(
                            left: 252.0,
                            top: 100.0,
                            right: null,
                            bottom: null,
                            width: 851.0,
                            height: 62.0,
                            child: GeneratedViewtheprototypeWidget(),
                          ),
                          Positioned(
                            left: 252.0,
                            top: 192.0,
                            right: null,
                            bottom: null,
                            width: 851.0,
                            height: 70.0,
                            child:
                                GeneratedGetstartedbyclickingtheplayiconinthetoprightoftheeditor(),
                          ),
                          Positioned(
                            left: 252.0,
                            top: 380.0,
                            right: null,
                            bottom: null,
                            width: 851.0,
                            height: 62.0,
                            child: GeneratedSeehowitworksWidget1(),
                          ),
                          Positioned(
                            left: 252.0,
                            top: 472.0,
                            right: null,
                            bottom: null,
                            width: 851.0,
                            height: 70.0,
                            child:
                                GeneratedTakealookathowtheseprototypesaremadeandwhatsettingsandf(),
                          ),
                          Positioned(
                            left: 252.0,
                            top: 620.0,
                            right: null,
                            bottom: null,
                            width: 849.0,
                            height: 314.0,
                            child: GeneratedPresetSizesWidget(),
                          ),
                          Positioned(
                            left: 252.0,
                            top: 974.0,
                            right: null,
                            bottom: null,
                            width: 849.0,
                            height: 314.0,
                            child: GeneratedPresetSizesWidget1(),
                          ),
                          Positioned(
                            left: 252.0,
                            top: 1328.0,
                            right: null,
                            bottom: null,
                            width: 849.0,
                            height: 314.0,
                            child: GeneratedPresetSizesWidget2(),
                          ),
                          Positioned(
                            left: 252.0,
                            top: 1682.0,
                            right: null,
                            bottom: null,
                            width: 849.0,
                            height: 314.0,
                            child: GeneratedPresetSizesWidget3(),
                          ),
                          Positioned(
                            left: 252.0,
                            top: 2036.0,
                            right: null,
                            bottom: null,
                            width: 849.0,
                            height: 314.0,
                            child: GeneratedPresetSizesWidget4(),
                          ),
                          Positioned(
                            left: 1191.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 8111.0,
                            height: 3352.0,
                            child: GeneratedRightPanelWidget(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
