import 'package:flutter/material.dart';
import 'package:flutterapp/testeapp/generatedchatswidget/generated/GeneratedEllipseWidget17.dart';
import 'package:flutterapp/testeapp/generatedchatswidget/generated/GeneratedTabBarWidget4.dart';
import 'package:flutterapp/testeapp/generatedchatswidget/generated/GeneratedGroupWidget2.dart';
import 'package:flutterapp/testeapp/generatedchatswidget/generated/GeneratedBackgroundWidget145.dart';
import 'package:flutterapp/testeapp/generatedchatswidget/generated/GeneratedIknowImtryingtogetthefundsWidget.dart';
import 'package:flutterapp/testeapp/generatedchatswidget/generated/GeneratedRevShawnWidget.dart';
import 'package:flutterapp/testeapp/generatedchatswidget/generated/GeneratedBackgroundWidget142.dart';
import 'package:flutterapp/testeapp/generatedchatswidget/generated/GeneratedBackgroundWidget144.dart';
import 'package:flutterapp/testeapp/generatedchatswidget/generated/GeneratedWantedtoaskifyoureavailableforaportraitshootnextweekWid.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/testeapp/generatedchatswidget/generated/GeneratedWillKennyWidget.dart';
import 'package:flutterapp/testeapp/generatedchatswidget/generated/GeneratedStatusBarWidget9.dart';
import 'package:flutterapp/testeapp/generatedchatswidget/generated/GeneratedBackgroundWidget143.dart';
import 'package:flutterapp/testeapp/generatedchatswidget/generated/GeneratedImlookingfortipsaroundcapturingthemilkywayIhavea6Dwitha.dart';
import 'package:flutterapp/testeapp/generatedchatswidget/generated/GeneratedRectangleWidget20.dart';
import 'package:flutterapp/testeapp/generatedchatswidget/generated/GeneratedEllipseWidget18.dart';
import 'package:flutterapp/testeapp/generatedchatswidget/generated/GeneratedEllipseWidget19.dart';
import 'package:flutterapp/testeapp/generatedchatswidget/generated/GeneratedBethWilliamsWidget.dart';
import 'package:flutterapp/testeapp/generatedchatswidget/generated/GeneratedNavigationBarWidget1.dart';

/* Frame Chats
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChatsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 812.0,
                      child: GeneratedRectangleWidget20(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth;

                        final double height =
                            constraints.maxHeight * 0.10837438423645321;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: 0,
                              y: 0,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedNavigationBarWidget1(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth;

                        final double height =
                            constraints.maxHeight * 0.0006157635467980296;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: 0,
                              y: constraints.maxHeight * 0.2315270935960591,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedBackgroundWidget142(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth;

                        final double height =
                            constraints.maxHeight * 0.0006157635467980296;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: 0,
                              y: constraints.maxHeight * 0.35467980295566504,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedBackgroundWidget143(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth;

                        final double height =
                            constraints.maxHeight * 0.0006157635467980296;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: 0,
                              y: constraints.maxHeight * 0.47783251231527096,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedBackgroundWidget144(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth;

                        final double height =
                            constraints.maxHeight * 0.0006157635467980296;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: 0,
                              y: constraints.maxHeight * 0.6009852216748769,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedBackgroundWidget145(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 104.0,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 64.0,
                      child: GeneratedGroupWidget2(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.7066666666666667;

                        final double height =
                            constraints.maxHeight * 0.046798029556650245;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.256,
                              y: constraints.maxHeight * 0.28201970443349755,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child:
                                    GeneratedIknowImtryingtogetthefundsWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.7066666666666667;

                        final double height =
                            constraints.maxHeight * 0.024630541871921183;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.256,
                              y: constraints.maxHeight * 0.2524630541871921,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedWillKennyWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.7066666666666667;

                        final double height =
                            constraints.maxHeight * 0.046798029556650245;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.256,
                              y: constraints.maxHeight * 0.4051724137931034,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child:
                                    GeneratedImlookingfortipsaroundcapturingthemilkywayIhavea6Dwitha(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.7066666666666667;

                        final double height =
                            constraints.maxHeight * 0.024630541871921183;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.256,
                              y: constraints.maxHeight * 0.37561576354679804,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedBethWilliamsWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.7066666666666667;

                        final double height =
                            constraints.maxHeight * 0.046798029556650245;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.256,
                              y: constraints.maxHeight * 0.5283251231527094,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child:
                                    GeneratedWantedtoaskifyoureavailableforaportraitshootnextweekWid(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.7066666666666667;

                        final double height =
                            constraints.maxHeight * 0.024630541871921183;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.256,
                              y: constraints.maxHeight * 0.4987684729064039,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedRevShawnWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 205.0,
                      right: null,
                      bottom: null,
                      width: 64.0,
                      height: 64.0,
                      child: GeneratedEllipseWidget17(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 305.0,
                      right: null,
                      bottom: null,
                      width: 64.0,
                      height: 64.0,
                      child: GeneratedEllipseWidget18(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 405.0,
                      right: null,
                      bottom: null,
                      width: 64.0,
                      height: 64.0,
                      child: GeneratedEllipseWidget19(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: 0.0,
              width: 375.0,
              height: 83.0,
              child: GeneratedTabBarWidget4(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedStatusBarWidget9(),
            )
          ]),
    ));
  }
}
