import 'package:flutter/material.dart';
import 'package:flutterapp/testeapp/generateddiscoveroverflowbehaviorwidget/generated/GeneratedRectangle21Widget16.dart';
import 'package:flutterapp/testeapp/generateddiscoveroverflowbehaviorwidget/generated/GeneratedRectangle210Widget3.dart';
import 'package:flutterapp/testeapp/generateddiscoveroverflowbehaviorwidget/generated/GeneratedRectangle2Widget26.dart';
import 'package:flutterapp/testeapp/generateddiscoveroverflowbehaviorwidget/generated/GeneratedButtonWidget10.dart';
import 'package:flutterapp/testeapp/generateddiscoveroverflowbehaviorwidget/generated/GeneratedRectangle29Widget3.dart';
import 'package:flutterapp/testeapp/generateddiscoveroverflowbehaviorwidget/generated/GeneratedRectangle24Widget3.dart';
import 'package:flutterapp/testeapp/generateddiscoveroverflowbehaviorwidget/generated/GeneratedRectangle22Widget4.dart';
import 'package:flutterapp/testeapp/generateddiscoveroverflowbehaviorwidget/generated/GeneratedRectangle3Widget4.dart';
import 'package:flutterapp/testeapp/generateddiscoveroverflowbehaviorwidget/generated/GeneratedTabBarWidget5.dart';
import 'package:flutterapp/testeapp/generateddiscoveroverflowbehaviorwidget/generated/GeneratedRectangle25Widget3.dart';
import 'package:flutterapp/testeapp/generateddiscoveroverflowbehaviorwidget/generated/GeneratedStatusBarWidget10.dart';
import 'package:flutterapp/testeapp/generateddiscoveroverflowbehaviorwidget/generated/GeneratedWhatsnewtodayWidget.dart';
import 'package:flutterapp/testeapp/generateddiscoveroverflowbehaviorwidget/generated/GeneratedFrameWidget.dart';
import 'package:flutterapp/testeapp/generateddiscoveroverflowbehaviorwidget/generated/GeneratedRectangle27Widget2.dart';
import 'package:flutterapp/testeapp/generateddiscoveroverflowbehaviorwidget/generated/GeneratedRectangle26Widget2.dart';
import 'package:flutterapp/testeapp/generateddiscoveroverflowbehaviorwidget/generated/GeneratedRegisterWidget10.dart';
import 'package:flutterapp/testeapp/generateddiscoveroverflowbehaviorwidget/generated/GeneratedRectangle23Widget3.dart';
import 'package:flutterapp/testeapp/generateddiscoveroverflowbehaviorwidget/generated/GeneratedBrowseallWidget.dart';

/* Frame Discover (overflow behavior)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDiscoveroverflowbehaviorWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
          LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            return SingleChildScrollView(
              scrollDirection: Axis.vertical,
              child: Container(
                  height: 2267.0,
                  child: Stack(children: [
                    Container(
                        width: constraints.maxWidth,
                        child: Container(
                          width: 375.0,
                          height: 2267.0,
                          child: Stack(
                              fit: StackFit.expand,
                              alignment: Alignment.center,
                              overflow: Overflow.visible,
                              children: [
                                ClipRRect(
                                  borderRadius: BorderRadius.zero,
                                  child: Container(
                                    color: Color.fromARGB(255, 255, 255, 255),
                                  ),
                                ),
                                Positioned(
                                  left: 0.0,
                                  top: 0.0,
                                  right: null,
                                  bottom: null,
                                  width: 375.0,
                                  height: 2267.0,
                                  child: GeneratedRectangle3Widget4(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 661.0,
                                  right: null,
                                  bottom: null,
                                  width: 167.0,
                                  height: 220.0,
                                  child: GeneratedRectangle2Widget26(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 187.0,
                                  right: null,
                                  bottom: null,
                                  width: 343.0,
                                  height: 387.0,
                                  child: GeneratedFrameWidget(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 148.0,
                                  right: null,
                                  bottom: null,
                                  width: 134.0,
                                  height: 17.0,
                                  child: GeneratedWhatsnewtodayWidget(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 622.0,
                                  right: null,
                                  bottom: null,
                                  width: 86.0,
                                  height: 17.0,
                                  child: GeneratedBrowseallWidget(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 1210.0,
                                  right: null,
                                  bottom: null,
                                  width: 167.0,
                                  height: 220.0,
                                  child: GeneratedRectangle24Widget3(),
                                ),
                                Positioned(
                                  left: 192.0,
                                  top: 1300.0,
                                  right: null,
                                  bottom: null,
                                  width: 167.0,
                                  height: 220.0,
                                  child: GeneratedRectangle25Widget3(),
                                ),
                                Positioned(
                                  left: 192.0,
                                  top: 1848.0,
                                  right: null,
                                  bottom: null,
                                  width: 167.0,
                                  height: 220.0,
                                  child: GeneratedRectangle210Widget3(),
                                ),
                                Positioned(
                                  left: 192.0,
                                  top: 661.0,
                                  right: null,
                                  bottom: null,
                                  width: 167.0,
                                  height: 310.0,
                                  child: GeneratedRectangle21Widget16(),
                                ),
                                Positioned(
                                  left: 192.0,
                                  top: 981.0,
                                  right: null,
                                  bottom: null,
                                  width: 167.0,
                                  height: 310.0,
                                  child: GeneratedRectangle23Widget3(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 1439.0,
                                  right: null,
                                  bottom: null,
                                  width: 167.0,
                                  height: 310.0,
                                  child: GeneratedRectangle26Widget2(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 1758.0,
                                  right: null,
                                  bottom: null,
                                  width: 167.0,
                                  height: 310.0,
                                  child: GeneratedRectangle29Widget3(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 2100.0,
                                  right: null,
                                  bottom: null,
                                  width: 343.0,
                                  height: 52.0,
                                  child: GeneratedButtonWidget10(),
                                ),
                                Positioned(
                                  left: 192.0,
                                  top: 1529.0,
                                  right: null,
                                  bottom: null,
                                  width: 167.0,
                                  height: 310.0,
                                  child: GeneratedRectangle27Widget2(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 891.0,
                                  right: null,
                                  bottom: null,
                                  width: 167.0,
                                  height: 310.0,
                                  child: GeneratedRectangle22Widget4(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 76.0,
                                  right: null,
                                  bottom: null,
                                  width: 148.0,
                                  height: 40.0,
                                  child: GeneratedRegisterWidget10(),
                                )
                              ]),
                        ))
                  ])),
            );
          }),
          Positioned(
            left: 0.0,
            top: null,
            right: null,
            bottom: 0.0,
            width: 375.0,
            height: 83.0,
            child: GeneratedTabBarWidget5(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 44.0,
            child: GeneratedStatusBarWidget10(),
          )
        ]));
  }
}
