import 'package:flutter/material.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedRegisterWidget8.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedRectangle212Widget.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedRectangle211Widget.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedRectangle24Widget1.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedRectangle210Widget.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedRectangle25Widget1.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedAllresultsWidget.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedRectangle2Widget18.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedTabBarWidget1.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedComponentWidget7.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedRectangle22Widget1.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedRectangle21Widget5.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedStatusBarWidget6.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedRectangle214Widget.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedRectangle213Widget.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedRectangle23Widget1.dart';
import 'package:flutterapp/testeapp/generatedsearchresultswidget/generated/GeneratedButtonWidget8.dart';

/* Frame Search results
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchresultsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
          LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            return SingleChildScrollView(
              scrollDirection: Axis.vertical,
              child: Container(
                  height: 1049.0,
                  child: Stack(children: [
                    Container(
                        width: constraints.maxWidth,
                        child: Container(
                          width: 375.0,
                          height: 1049.0,
                          child: Stack(
                              fit: StackFit.expand,
                              alignment: Alignment.center,
                              overflow: Overflow.visible,
                              children: [
                                ClipRRect(
                                  borderRadius: BorderRadius.zero,
                                  child: Container(
                                    color: Color.fromARGB(255, 255, 255, 255),
                                  ),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 76.0,
                                  right: null,
                                  bottom: null,
                                  width: 148.0,
                                  height: 40.0,
                                  child: GeneratedRegisterWidget8(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 148.0,
                                  right: null,
                                  bottom: null,
                                  width: 343.0,
                                  height: 52.0,
                                  child: GeneratedComponentWidget7(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 232.0,
                                  right: null,
                                  bottom: null,
                                  width: 88.0,
                                  height: 17.0,
                                  child: GeneratedAllresultsWidget(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 271.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle2Widget18(),
                                ),
                                Positioned(
                                  left: 134.0,
                                  top: 271.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle21Widget5(),
                                ),
                                Positioned(
                                  left: 252.0,
                                  top: 271.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle22Widget1(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 389.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle23Widget1(),
                                ),
                                Positioned(
                                  left: 134.0,
                                  top: 389.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle24Widget1(),
                                ),
                                Positioned(
                                  left: 252.0,
                                  top: 389.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle25Widget1(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 507.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle26Widget(),
                                ),
                                Positioned(
                                  left: 134.0,
                                  top: 507.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle27Widget(),
                                ),
                                Positioned(
                                  left: 252.0,
                                  top: 507.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle28Widget(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 625.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle29Widget(),
                                ),
                                Positioned(
                                  left: 134.0,
                                  top: 625.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle210Widget(),
                                ),
                                Positioned(
                                  left: 252.0,
                                  top: 625.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle211Widget(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 743.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle212Widget(),
                                ),
                                Positioned(
                                  left: 134.0,
                                  top: 743.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle213Widget(),
                                ),
                                Positioned(
                                  left: 252.0,
                                  top: 743.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle214Widget(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 882.0,
                                  right: null,
                                  bottom: null,
                                  width: 343.0,
                                  height: 52.0,
                                  child: GeneratedButtonWidget8(),
                                )
                              ]),
                        ))
                  ])),
            );
          }),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 44.0,
            child: GeneratedStatusBarWidget6(),
          ),
          Positioned(
            left: 0.0,
            top: null,
            right: null,
            bottom: 0.0,
            width: 375.0,
            height: 83.0,
            child: GeneratedTabBarWidget1(),
          )
        ]));
  }
}
