import 'package:flutter/material.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle22Widget2.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle2Widget21.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle216Widget.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle28Widget1.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedTabBarWidget2.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle222Widget.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle220Widget.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle214Widget1.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedStatusBarWidget7.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedButtonWidget9.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedAllresultsWidget1.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle212Widget1.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRegisterWidget9.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle21Widget8.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle25Widget2.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedComponentWidget8.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle219Widget.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle211Widget1.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle215Widget.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle27Widget1.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle223Widget.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle29Widget1.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle213Widget1.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle218Widget.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle221Widget.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle210Widget1.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle217Widget.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle24Widget2.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle23Widget2.dart';
import 'package:flutterapp/testeapp/generatedsearchresultspreservescrollpositionwidget/generated/GeneratedRectangle26Widget1.dart';

/* Frame Search results (preserve scroll position)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchresultspreservescrollpositionWidget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
          LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            return SingleChildScrollView(
              scrollDirection: Axis.vertical,
              child: Container(
                  height: 1403.0,
                  child: Stack(children: [
                    Container(
                        width: constraints.maxWidth,
                        child: Container(
                          width: 375.0,
                          height: 1403.0,
                          child: Stack(
                              fit: StackFit.expand,
                              alignment: Alignment.center,
                              overflow: Overflow.visible,
                              children: [
                                ClipRRect(
                                  borderRadius: BorderRadius.zero,
                                  child: Container(
                                    color: Color.fromARGB(255, 255, 255, 255),
                                  ),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 76.0,
                                  right: null,
                                  bottom: null,
                                  width: 148.0,
                                  height: 40.0,
                                  child: GeneratedRegisterWidget9(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 148.0,
                                  right: null,
                                  bottom: null,
                                  width: 343.0,
                                  height: 52.0,
                                  child: GeneratedComponentWidget8(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 232.0,
                                  right: null,
                                  bottom: null,
                                  width: 88.0,
                                  height: 17.0,
                                  child: GeneratedAllresultsWidget1(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 271.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle2Widget21(),
                                ),
                                Positioned(
                                  left: 134.0,
                                  top: 271.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle21Widget8(),
                                ),
                                Positioned(
                                  left: 252.0,
                                  top: 271.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle22Widget2(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 389.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle23Widget2(),
                                ),
                                Positioned(
                                  left: 134.0,
                                  top: 389.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle24Widget2(),
                                ),
                                Positioned(
                                  left: 252.0,
                                  top: 389.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle25Widget2(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 507.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle26Widget1(),
                                ),
                                Positioned(
                                  left: 134.0,
                                  top: 507.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle27Widget1(),
                                ),
                                Positioned(
                                  left: 252.0,
                                  top: 507.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle28Widget1(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 625.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle29Widget1(),
                                ),
                                Positioned(
                                  left: 134.0,
                                  top: 625.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle210Widget1(),
                                ),
                                Positioned(
                                  left: 252.0,
                                  top: 625.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle211Widget1(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 743.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle212Widget1(),
                                ),
                                Positioned(
                                  left: 134.0,
                                  top: 743.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle213Widget1(),
                                ),
                                Positioned(
                                  left: 252.0,
                                  top: 743.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle214Widget1(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 861.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle215Widget(),
                                ),
                                Positioned(
                                  left: 134.0,
                                  top: 861.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle216Widget(),
                                ),
                                Positioned(
                                  left: 252.0,
                                  top: 861.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle217Widget(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 979.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle218Widget(),
                                ),
                                Positioned(
                                  left: 134.0,
                                  top: 979.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle219Widget(),
                                ),
                                Positioned(
                                  left: 252.0,
                                  top: 979.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle220Widget(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 1097.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle221Widget(),
                                ),
                                Positioned(
                                  left: 134.0,
                                  top: 1097.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle222Widget(),
                                ),
                                Positioned(
                                  left: 252.0,
                                  top: 1097.0,
                                  right: null,
                                  bottom: null,
                                  width: 107.0,
                                  height: 107.0,
                                  child: GeneratedRectangle223Widget(),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 1236.0,
                                  right: null,
                                  bottom: null,
                                  width: 343.0,
                                  height: 52.0,
                                  child: GeneratedButtonWidget9(),
                                )
                              ]),
                        ))
                  ])),
            );
          }),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 44.0,
            child: GeneratedStatusBarWidget7(),
          ),
          Positioned(
            left: 0.0,
            top: null,
            right: null,
            bottom: 0.0,
            width: 375.0,
            height: 83.0,
            child: GeneratedTabBarWidget2(),
          )
        ]));
  }
}
