import 'package:flutter/material.dart';
import 'package:flutterapp/testeapp/generatedloginwidget1/generated/GeneratedRectangleWidget9.dart';
import 'package:flutterapp/testeapp/generatedloginwidget1/generated/GeneratedUnionWidget10.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/testeapp/generatedloginwidget1/generated/GeneratedKeyboardWidget4.dart';
import 'package:flutterapp/testeapp/generatedloginwidget1/generated/GeneratedStatusBarWidget3.dart';
import 'package:flutterapp/testeapp/generatedloginwidget1/generated/GeneratedComponentWidget4.dart';
import 'package:flutterapp/testeapp/generatedloginwidget1/generated/GeneratedButtonWidget4.dart';
import 'package:flutterapp/testeapp/generatedloginwidget1/generated/GeneratedRegisterWidget6.dart';
import 'package:flutterapp/testeapp/generatedloginwidget1/generated/GeneratedComponentWidget5.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 812.0,
                      child: GeneratedRectangleWidget9(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 176.0,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 52.0,
                      child: GeneratedComponentWidget4(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 244.0,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 52.0,
                      child: GeneratedComponentWidget5(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 312.0,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 52.0,
                      child: GeneratedButtonWidget4(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth;

                        final double height =
                            constraints.maxHeight * 0.3583743842364532;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: 0,
                              y: constraints.maxHeight * 0.6416256157635468,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedKeyboardWidget4(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 104.0,
                      right: null,
                      bottom: null,
                      width: 148.0,
                      height: 40.0,
                      child: GeneratedRegisterWidget6(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 60.0,
                      right: null,
                      bottom: null,
                      width: 12.207107543945312,
                      height: 11.353558540344238,
                      child: GeneratedUnionWidget10(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedStatusBarWidget3(),
            )
          ]),
    ));
  }
}
