import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/testeapp/generatedregisterstep2widget/generated/GeneratedButtonWidget3.dart';
import 'package:flutterapp/testeapp/generatedregisterstep2widget/generated/GeneratedBysigningupyouagreetoPhotosTermsofServiceandPrivacyPoli.dart';
import 'package:flutterapp/testeapp/generatedregisterstep2widget/generated/GeneratedComponentWidget3.dart';
import 'package:flutterapp/testeapp/generatedregisterstep2widget/generated/GeneratedRegisterWidget4.dart';
import 'package:flutterapp/testeapp/generatedregisterstep2widget/generated/GeneratedStatusBarWidget2.dart';
import 'package:flutterapp/testeapp/generatedregisterstep2widget/generated/GeneratedKeyboardWidget2.dart';
import 'package:flutterapp/testeapp/generatedregisterstep2widget/generated/GeneratedRectangleWidget8.dart';
import 'package:flutterapp/testeapp/generatedregisterstep2widget/generated/GeneratedUnionWidget8.dart';

/* Frame Register (step 2)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegisterstep2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 812.0,
                      child: GeneratedRectangleWidget8(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 104.0,
                      right: null,
                      bottom: null,
                      width: 148.0,
                      height: 40.0,
                      child: GeneratedRegisterWidget4(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 176.0,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 52.0,
                      child: GeneratedComponentWidget3(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 244.0,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 52.0,
                      child: GeneratedButtonWidget3(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 328.0,
                      right: null,
                      bottom: null,
                      width: 345.0,
                      height: 38.0,
                      child:
                          GeneratedBysigningupyouagreetoPhotosTermsofServiceandPrivacyPoli(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth;

                        final double height =
                            constraints.maxHeight * 0.3583743842364532;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: 0,
                              y: constraints.maxHeight * 0.6416256157635468,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedKeyboardWidget2(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 60.0,
                      right: null,
                      bottom: null,
                      width: 12.207107543945312,
                      height: 11.353558540344238,
                      child: GeneratedUnionWidget8(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedStatusBarWidget2(),
            )
          ]),
    ));
  }
}
