import 'package:flutter/material.dart';
import 'package:flutterapp/testeapp/generatedsearchwidget/generated/GeneratedRegisterWidget7.dart';
import 'package:flutterapp/testeapp/generatedsearchwidget/generated/GeneratedStatusBarWidget5.dart';
import 'package:flutterapp/testeapp/generatedsearchwidget/generated/GeneratedRectangleWidget12.dart';
import 'package:flutterapp/testeapp/generatedsearchwidget/generated/GeneratedComponentWidget6.dart';

/* Frame Search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget12(),
              ),
              Positioned(
                left: 16.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 40.0,
                child: GeneratedRegisterWidget7(),
              ),
              Positioned(
                left: 16.0,
                top: 148.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedComponentWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBarWidget5(),
              )
            ]),
      ),
    ));
  }
}
