import 'package:flutter/material.dart';
import 'package:flutterapp/testeapp/generatedphotoopenoverlaywidget1/generated/GeneratedRectangle2Widget24.dart';
import 'package:flutterapp/testeapp/generatedphotoopenoverlaywidget1/generated/Generated32xWidget1.dart';
import 'package:flutterapp/testeapp/generatedphotoopenoverlaywidget1/generated/GeneratedRectangleWidget17.dart';
import 'package:flutterapp/testeapp/generatedphotoopenoverlaywidget1/generated/GeneratedComponentWidget10.dart';

/* Frame Photo open (overlay)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPhotoopenoverlayWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget17(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 300.0,
                child: GeneratedRectangle2Widget24(),
              ),
              Positioned(
                left: 329.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: Generated32xWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 28.0,
                child: GeneratedComponentWidget10(),
              )
            ]),
      ),
    ));
  }
}
